version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - auth-service
      - travel-service
      - carbon-service
      - rewards-service

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/convidat-auth
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb

  travel-service:
    build:
      context: ./services/travel-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/convidat-travel
    depends_on:
      - mongodb

  carbon-service:
    build:
      context: ./services/carbon-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/convidat-carbon
    depends_on:
      - mongodb

  rewards-service:
    build:
      context: ./services/rewards-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/convidat-rewards
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 